CREATE TABLE FLIGHT_SESSION (
  SESSION_ID                VARCHAR2(64) PRIMARY KEY,
  SCENARIO_ID               VARCHAR2(100),
  PILOT_ID                  VARCHAR2(100),
  SESSION_STATUS            VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
  STARTED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ENDED_AT                  TIMESTAMP,
  SCREEN_WIDTH              NUMBER,
  SCREEN_HEIGHT             NUMBER,
  GRID_COLS                 NUMBER DEFAULT 40 NOT NULL,
  GRID_ROWS                 NUMBER DEFAULT 24 NOT NULL,
  TOTAL_SAMPLES             NUMBER DEFAULT 0 NOT NULL,
  TOTAL_FIXATIONS           NUMBER DEFAULT 0 NOT NULL,
  TOTAL_GAZE_DURATION_MS    NUMBER DEFAULT 0 NOT NULL,
  NOTES                     VARCHAR2(500),

  CONSTRAINT CHK_FLIGHT_SESSION_STATUS
    CHECK (SESSION_STATUS IN ('ACTIVE', 'COMPLETED', 'ABORTED'))
);

CREATE TABLE GAZE_SAMPLE (
  SAMPLE_ID                 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SESSION_ID                VARCHAR2(64) NOT NULL,
  TS_MS                     NUMBER NOT NULL,
  ELAPSED_MS                NUMBER,
  X                         NUMBER(10,2) NOT NULL,
  Y                         NUMBER(10,2) NOT NULL,
  NX                        NUMBER(8,4),
  NY                        NUMBER(8,4),
  AOI                       VARCHAR2(64),
  CONFIDENCE                NUMBER(5,4),
  GRID_X                    NUMBER,
  GRID_Y                    NUMBER,
  IS_VALID                  NUMBER(1) DEFAULT 1 NOT NULL,
  INVALID_REASON            VARCHAR2(100),
  CREATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT FK_GAZE_SAMPLE_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID),

  CONSTRAINT CHK_GAZE_SAMPLE_VALID
    CHECK (IS_VALID IN (0, 1)),

  CONSTRAINT CHK_GAZE_SAMPLE_CONFIDENCE
    CHECK (CONFIDENCE IS NULL OR (CONFIDENCE >= 0 AND CONFIDENCE <= 1))
);

CREATE TABLE GAZE_FIXATION (
  FIXATION_ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SESSION_ID                VARCHAR2(64) NOT NULL,
  AOI                       VARCHAR2(64),
  START_TS_MS               NUMBER NOT NULL,
  END_TS_MS                 NUMBER NOT NULL,
  DURATION_MS               NUMBER NOT NULL,
  CENTER_X                  NUMBER(10,2),
  CENTER_Y                  NUMBER(10,2),
  CENTER_NX                 NUMBER(8,4),
  CENTER_NY                 NUMBER(8,4),
  GRID_X                    NUMBER,
  GRID_Y                    NUMBER,
  SAMPLE_COUNT              NUMBER DEFAULT 0 NOT NULL,
  IS_VERIFIED_LOOK          NUMBER(1) DEFAULT 0 NOT NULL,
  VERIFY_RULE_ID            VARCHAR2(64),
  CREATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT FK_GAZE_FIXATION_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID),

  CONSTRAINT CHK_GAZE_FIXATION_VERIFY
    CHECK (IS_VERIFIED_LOOK IN (0, 1)),

  CONSTRAINT CHK_GAZE_FIXATION_TIME
    CHECK (END_TS_MS >= START_TS_MS),

  CONSTRAINT CHK_GAZE_FIXATION_DURATION
    CHECK (DURATION_MS >= 0)
);

CREATE TABLE AOI_AGGREGATE (
  SESSION_ID                VARCHAR2(64) NOT NULL,
  AOI                       VARCHAR2(64) NOT NULL,
  SAMPLE_COUNT              NUMBER DEFAULT 0 NOT NULL,
  FIXATION_COUNT            NUMBER DEFAULT 0 NOT NULL,
  TOTAL_DWELL_MS            NUMBER DEFAULT 0 NOT NULL,
  AVG_FIXATION_MS           NUMBER DEFAULT 0 NOT NULL,
  LONGEST_FIXATION_MS       NUMBER DEFAULT 0 NOT NULL,
  FIRST_LOOK_TS_MS          NUMBER,
  LAST_LOOK_TS_MS           NUMBER,
  LOOK_VERIFIED_COUNT       NUMBER DEFAULT 0 NOT NULL,
  LAST_UPDATED              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_AOI_AGGREGATE
    PRIMARY KEY (SESSION_ID, AOI),

  CONSTRAINT FK_AOI_AGG_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID),

  CONSTRAINT CHK_AOI_AGG_TIMES
    CHECK (
      FIRST_LOOK_TS_MS IS NULL
      OR LAST_LOOK_TS_MS IS NULL
      OR LAST_LOOK_TS_MS >= FIRST_LOOK_TS_MS
    )
);

CREATE TABLE HEATMAP_CELL_AGGREGATE (
  SESSION_ID                VARCHAR2(64) NOT NULL,
  GRID_X                    NUMBER NOT NULL,
  GRID_Y                    NUMBER NOT NULL,
  SAMPLE_COUNT              NUMBER DEFAULT 0 NOT NULL,
  TOTAL_DWELL_MS            NUMBER DEFAULT 0 NOT NULL,
  FIXATION_COUNT            NUMBER DEFAULT 0 NOT NULL,
  LAST_UPDATED              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_HEATMAP_CELL_AGGREGATE
    PRIMARY KEY (SESSION_ID, GRID_X, GRID_Y),

  CONSTRAINT FK_HEATMAP_AGG_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID)
);

CREATE TABLE AOI_RULE (
  RULE_ID                   VARCHAR2(64) PRIMARY KEY,
  SCENARIO_ID               VARCHAR2(100) NOT NULL,
  AOI                       VARCHAR2(64) NOT NULL,
  RULE_NAME                 VARCHAR2(200),
  RULE_MODE                 VARCHAR2(30) DEFAULT 'HYBRID' NOT NULL,
  MIN_DWELL_MS              NUMBER,
  MIN_FIXATION_COUNT        NUMBER,
  MIN_SUSTAINED_FIXATION_MS NUMBER,
  MAX_ALLOWED_GAP_MS        NUMBER,
  REQUIRED_ORDER_NO         NUMBER,
  IS_REQUIRED               NUMBER(1) DEFAULT 1 NOT NULL,
  DESCRIPTION               VARCHAR2(500),

  CONSTRAINT CHK_AOI_RULE_REQUIRED
    CHECK (IS_REQUIRED IN (0, 1)),

  CONSTRAINT CHK_AOI_RULE_MODE
    CHECK (RULE_MODE IN ('CUMULATIVE_DWELL', 'SUSTAINED_FIXATION', 'FIXATION_COUNT', 'HYBRID')),

  CONSTRAINT CHK_AOI_RULE_THRESHOLDS
    CHECK (
      (MIN_DWELL_MS IS NULL OR MIN_DWELL_MS >= 0) AND
      (MIN_FIXATION_COUNT IS NULL OR MIN_FIXATION_COUNT >= 0) AND
      (MIN_SUSTAINED_FIXATION_MS IS NULL OR MIN_SUSTAINED_FIXATION_MS >= 0) AND
      (MAX_ALLOWED_GAP_MS IS NULL OR MAX_ALLOWED_GAP_MS >= 0) AND
      (REQUIRED_ORDER_NO IS NULL OR REQUIRED_ORDER_NO >= 1)
    )
);

CCREATE TABLE AOI_RULE_RESULT (
  RESULT_ID                 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SESSION_ID                VARCHAR2(64) NOT NULL,
  RULE_ID                   VARCHAR2(64) NOT NULL,
  AOI                       VARCHAR2(64) NOT NULL,
  PASSED                    NUMBER(1) DEFAULT 0 NOT NULL,
  ACTUAL_DWELL_MS           NUMBER DEFAULT 0 NOT NULL,
  ACTUAL_FIXATION_COUNT     NUMBER DEFAULT 0 NOT NULL,
  LONGEST_FIXATION_MS       NUMBER DEFAULT 0 NOT NULL,
  FIRST_SATISFIED_TS_MS     NUMBER,
  EVALUATED_AT              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT FK_RULE_RESULT_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID),

  CONSTRAINT FK_RULE_RESULT_RULE
    FOREIGN KEY (RULE_ID) REFERENCES AOI_RULE(RULE_ID),

  CONSTRAINT UK_RULE_RESULT_SESSION_RULE
    UNIQUE (SESSION_ID, RULE_ID),

  CONSTRAINT CHK_RULE_RESULT_PASSED
    CHECK (PASSED IN (0, 1))
);

ALTER TABLE AOI_RULE
ADD (
  MIN_SUSTAINED_FIXATION_MS NUMBER,
  RULE_MODE VARCHAR2(30) DEFAULT 'HYBRID',
  MAX_ALLOWED_GAP_MS NUMBER
);

ALTER TABLE AOI_RULE DROP CONSTRAINT CHK_AOI_RULE_THRESHOLDS;

ALTER TABLE AOI_RULE
ADD CONSTRAINT CHK_AOI_RULE_THRESHOLDS
CHECK (
  (MIN_DWELL_MS IS NULL OR MIN_DWELL_MS >= 0) AND
  (MIN_FIXATION_COUNT IS NULL OR MIN_FIXATION_COUNT >= 0) AND
  (MIN_SUSTAINED_FIXATION_MS IS NULL OR MIN_SUSTAINED_FIXATION_MS >= 0) AND
  (MAX_ALLOWED_GAP_MS IS NULL OR MAX_ALLOWED_GAP_MS >= 0) AND
  (REQUIRED_ORDER_NO IS NULL OR REQUIRED_ORDER_NO >= 1)
);

ALTER TABLE AOI_RULE
ADD CONSTRAINT CHK_AOI_RULE_MODE
CHECK (RULE_MODE IN ('CUMULATIVE_DWELL', 'SUSTAINED_FIXATION', 'FIXATION_COUNT', 'HYBRID'));

ALTER TABLE AOI_RULE_RESULT
ADD (
  LONGEST_FIXATION_MS NUMBER DEFAULT 0 NOT NULL
);

ALTER TABLE AOI_AGGREGATE
ADD (
  VISIT_COUNT NUMBER DEFAULT 0 NOT NULL,
  AVG_VISIT_MS NUMBER DEFAULT 0 NOT NULL,
  LONGEST_VISIT_MS NUMBER DEFAULT 0 NOT NULL
);

CREATE TABLE AOI_VISIT (
  VISIT_ID                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SESSION_ID                VARCHAR2(64) NOT NULL,
  AOI                       VARCHAR2(64) NOT NULL,
  START_TS_MS               NUMBER NOT NULL,
  END_TS_MS                 NUMBER NOT NULL,
  DURATION_MS               NUMBER NOT NULL,
  FIXATION_COUNT            NUMBER DEFAULT 0 NOT NULL,
  FIRST_FIXATION_ID         NUMBER,
  LAST_FIXATION_ID          NUMBER,
  VISIT_ORDER_NO            NUMBER,
  CREATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT FK_AOI_VISIT_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID),

  CONSTRAINT CHK_AOI_VISIT_TIME
    CHECK (END_TS_MS >= START_TS_MS),

  CONSTRAINT CHK_AOI_VISIT_DURATION
    CHECK (DURATION_MS >= 0)
);

DELETE FROM AOI_RULE_RESULT;
DELETE FROM AOI_VISIT;
DELETE FROM HEATMAP_CELL_AGGREGATE;
DELETE FROM AOI_AGGREGATE;
DELETE FROM GAZE_FIXATION;
DELETE FROM GAZE_SAMPLE;
DELETE FROM AOI_RULE;
DELETE FROM FLIGHT_SESSION;

COMMIT;

SELECT 'AOI_RULE_RESULT' AS TABLE_NAME, COUNT(*) AS CNT FROM AOI_RULE_RESULT
UNION ALL
SELECT 'AOI_VISIT', COUNT(*) FROM AOI_VISIT
UNION ALL
SELECT 'HEATMAP_CELL_AGGREGATE', COUNT(*) FROM HEATMAP_CELL_AGGREGATE
UNION ALL
SELECT 'AOI_AGGREGATE', COUNT(*) FROM AOI_AGGREGATE
UNION ALL
SELECT 'GAZE_FIXATION', COUNT(*) FROM GAZE_FIXATION
UNION ALL
SELECT 'GAZE_SAMPLE', COUNT(*) FROM GAZE_SAMPLE
UNION ALL
SELECT 'AOI_RULE', COUNT(*) FROM AOI_RULE
UNION ALL
SELECT 'FLIGHT_SESSION', COUNT(*) FROM FLIGHT_SESSION;