CREATE TABLE FLIGHT_SESSION (
  SESSION_ID                VARCHAR2(64) PRIMARY KEY,
  SCENARIO_ID               VARCHAR2(100),
  PILOT_ID                  VARCHAR2(100),
  SESSION_STATUS            VARCHAR2(30) DEFAULT 'ACTIVE',
  STARTED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ENDED_AT                  TIMESTAMP,
  SCREEN_WIDTH              NUMBER,
  SCREEN_HEIGHT             NUMBER,
  GRID_COLS                 NUMBER DEFAULT 40,
  GRID_ROWS                 NUMBER DEFAULT 24,
  TOTAL_SAMPLES             NUMBER DEFAULT 0,
  TOTAL_FIXATIONS           NUMBER DEFAULT 0,
  TOTAL_GAZE_DURATION_MS    NUMBER DEFAULT 0,
  NOTES                     VARCHAR2(500)
);

CREATE TABLE GAZE_SAMPLE (
  SAMPLE_ID                 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SESSION_ID                VARCHAR2(64) NOT NULL,
  TS_MS                     NUMBER NOT NULL,
  ELAPSED_MS                NUMBER,
  X                         NUMBER(10,2) NOT NULL,
  Y                         NUMBER(10,2) NOT NULL,
  NX                        NUMBER(8,4),
  NY                        NUMBER(8,4),
  AOI                       VARCHAR2(64),
  CONFIDENCE                NUMBER(5,4),
  GRID_X                    NUMBER,
  GRID_Y                    NUMBER,
  IS_VALID                  NUMBER(1) DEFAULT 1,
  INVALID_REASON            VARCHAR2(100),
  CREATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_GAZE_SAMPLE_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID)
);

CREATE TABLE GAZE_FIXATION (
  FIXATION_ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SESSION_ID                VARCHAR2(64) NOT NULL,
  AOI                       VARCHAR2(64),
  START_TS_MS               NUMBER NOT NULL,
  END_TS_MS                 NUMBER NOT NULL,
  DURATION_MS               NUMBER NOT NULL,
  CENTER_X                  NUMBER(10,2),
  CENTER_Y                  NUMBER(10,2),
  CENTER_NX                 NUMBER(8,4),
  CENTER_NY                 NUMBER(8,4),
  GRID_X                    NUMBER,
  GRID_Y                    NUMBER,
  SAMPLE_COUNT              NUMBER DEFAULT 0,
  IS_VERIFIED_LOOK          NUMBER(1) DEFAULT 0,
  VERIFY_RULE_ID            VARCHAR2(64),
  CREATED_AT                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_GAZE_FIXATION_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID)
);

CREATE TABLE AOI_AGGREGATE (
  SESSION_ID                VARCHAR2(64) NOT NULL,
  AOI                       VARCHAR2(64) NOT NULL,
  SAMPLE_COUNT              NUMBER DEFAULT 0,
  FIXATION_COUNT            NUMBER DEFAULT 0,
  TOTAL_DWELL_MS            NUMBER DEFAULT 0,
  AVG_FIXATION_MS           NUMBER DEFAULT 0,
  LONGEST_FIXATION_MS       NUMBER DEFAULT 0,
  FIRST_LOOK_TS_MS          NUMBER,
  LAST_LOOK_TS_MS           NUMBER,
  LOOK_VERIFIED_COUNT       NUMBER DEFAULT 0,
  LAST_UPDATED              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (SESSION_ID, AOI),
  CONSTRAINT FK_AOI_AGG_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID)
);

CREATE TABLE HEATMAP_CELL_AGGREGATE (
  SESSION_ID                VARCHAR2(64) NOT NULL,
  GRID_X                    NUMBER NOT NULL,
  GRID_Y                    NUMBER NOT NULL,
  SAMPLE_COUNT              NUMBER DEFAULT 0,
  TOTAL_DWELL_MS            NUMBER DEFAULT 0,
  FIXATION_COUNT            NUMBER DEFAULT 0,
  LAST_UPDATED              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (SESSION_ID, GRID_X, GRID_Y),
  CONSTRAINT FK_HEATMAP_AGG_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID)
);

CREATE TABLE AOI_RULE (
  RULE_ID                   VARCHAR2(64) PRIMARY KEY,
  SCENARIO_ID               VARCHAR2(100) NOT NULL,
  AOI                       VARCHAR2(64) NOT NULL,
  RULE_NAME                 VARCHAR2(200),
  MIN_DWELL_MS              NUMBER,
  MIN_FIXATION_COUNT        NUMBER,
  REQUIRED_ORDER_NO         NUMBER,
  IS_REQUIRED               NUMBER(1) DEFAULT 1,
  DESCRIPTION               VARCHAR2(500)
);

CREATE TABLE AOI_RULE_RESULT (
  RESULT_ID                 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SESSION_ID                VARCHAR2(64) NOT NULL,
  RULE_ID                   VARCHAR2(64) NOT NULL,
  AOI                       VARCHAR2(64) NOT NULL,
  PASSED                    NUMBER(1) DEFAULT 0,
  ACTUAL_DWELL_MS           NUMBER DEFAULT 0,
  ACTUAL_FIXATION_COUNT     NUMBER DEFAULT 0,
  FIRST_SATISFIED_TS_MS     NUMBER,
  EVALUATED_AT              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_RULE_RESULT_SESSION
    FOREIGN KEY (SESSION_ID) REFERENCES FLIGHT_SESSION(SESSION_ID)
);